server:
  port: 8008
  servlet:
    context-path: /travel-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/travels
    
    driver-class-name: org.postgresql.Driver
    username: postgresql
    password: postgresql

